const KEYS={favorites:"math-class-tool-favorites-v1",recent:"math-class-tool-recent-v1",playlists:"math-class-playlists-v1"};
const PRESET_SCHEMA="math-class-preset/v1";
const rootPage=new URL("../index.html",location.href);
const state={tools:[],filtered:[],draft:[],playlists:read(KEYS.playlists,[]),view:"all",active:null,activeIndex:0,timerId:null,seconds:0,running:false,sharePreset:null};
const $=(selector)=>document.querySelector(selector);

function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
function escapeText(value){return String(value??"")}
function runtimeFor(id){if(id==="video-compressor")return["windows","offline"];if(id==="betting-game"||id==="monopoly-pricing-game")return["browser","internet"];if(id==="assignment-viewer")return["browser","offline","local-server"];if(id==="image-supervised-learning")return["browser","internet","camera"];if(id==="motion-shot")return["browser","offline","camera"];return["browser","offline"]}
function subjectOf(tags){const order=[["middle-school-1","중학교 수학1"],["middle-school-2","중학교 수학2"],["middle-school-3","중학교 수학3"],["common-math1","공통수학1"],["common-math2","공통수학2"],["algebra","대수"],["calculus","미적분"],["geometry","기하"],["probability-statistics","확률과 통계"],["ai-math","인공지능 수학"],["economic-math","경제 수학"],["school-work","학교 업무"]];return order.find(([tag])=>tags.includes(tag))?.[1]||"공통"}
function curriculumMeta(tags){let grade="공통";if(tags.includes("middle-school-1"))grade="중1";else if(tags.includes("middle-school-2"))grade="중2";else if(tags.includes("middle-school-3"))grade="중3";else if(tags.includes("common-math1")||tags.includes("common-math2"))grade="고등 공통";else if(["geometry","algebra","calculus","probability-statistics","ai-math","economic-math"].some(tag=>tags.includes(tag)))grade="고등 선택";const term=tags.includes("common-math1")?"1학기":tags.includes("common-math2")?"2학기":"전 학기";const topics=[["matrix","행렬","식의 계산"],["counting","경우의 수","곱셈 원리"],["inference","통계적 추론","확률분포"],["coordinate-geometry","좌표·도형","좌표와 식"],["probability","확률","비와 경우의 수"],["statistics","자료 분석","평균과 산포도"],["number-operations","수와 연산","정수·유리수"],["logic-reasoning","논리·추론","집합과 명제"],["finance-economy","금융·경제","비율과 함수"],["ai","인공지능·데이터","자료 표현"]];const found=topics.find(([tag])=>tags.includes(tag));return{grade,term,standard:found?.[1]||"수학적 탐구",prerequisite:found?.[2]||"해당 단원의 기본 개념"}}
function estimate(tags,id){const game=tags.includes("math-game"),deep=tags.includes("geometry")||tags.includes("calculus"),work=tags.includes("school-work");return{minutes:work?10:game?20:deep?40:30,difficulty:deep?"심화":game?"기초":"보통",group:game?"짝·모둠":work?"개인":"전체 학급",device:id==="video-compressor"?"Windows":id==="motion-shot"||id==="image-supervised-learning"?"카메라":work?"PC 권장":"모든 기기",...curriculumMeta(tags)}}
function normalize(value){return String(value||"").normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim()}

async function loadCatalog(){
  try{
    const response=await fetch(rootPage,{cache:"no-store"});if(!response.ok)throw new Error("catalog");
    const doc=new DOMParser().parseFromString(await response.text(),"text/html");
    state.tools=[...doc.querySelectorAll("[data-tool-id]")].map((card,index)=>{
      const tags=(card.dataset.toolTags||"").split(/\s+/).filter(Boolean);const links=[...card.querySelectorAll(".tool-footer a:not(.guide-link)")];const link=links.at(-1);const title=card.querySelector("h3")?.textContent.trim()||card.dataset.toolId;const meta=estimate(tags,card.dataset.toolId);
      return{id:card.dataset.toolId,title,description:card.querySelector(".tool-content>p")?.textContent.trim()||"",tags,path:link?.getAttribute("href")||"../",subject:subjectOf(tags),runtime:runtimeFor(card.dataset.toolId),order:index,...meta};
    });
    populateSubjects();applyFilters();renderPlaylists();importFromHash();
  }catch{ $("[data-result-count]").textContent="목록을 불러오지 못했습니다";$("[data-catalog-list]").innerHTML='<p class="empty">로컬 파일을 직접 연 경우 브라우저가 목록 읽기를 막을 수 있습니다. 이 폴더를 로컬 서버로 열어 주세요.</p>'; }
}

function populateSubjects(){const select=$("[data-filter=subject]");[...new Set(state.tools.map(t=>t.subject))].forEach(subject=>{const option=document.createElement("option");option.value=subject;option.textContent=subject;select.append(option)})}
function applyFilters(){
  const values=Object.fromEntries([...document.querySelectorAll("[data-filter]")].map(el=>[el.dataset.filter,el.value]));const query=normalize($("[data-search]").value);const favorites=new Set(read(KEYS.favorites,[]));const recent=read(KEYS.recent,[]);const recentOrder=new Map(recent.map((item,index)=>[item.id,index]));
  state.filtered=state.tools.filter(tool=>{
    if(state.view==="favorites"&&!favorites.has(tool.id))return false;if(state.view==="recent"&&!recentOrder.has(tool.id))return false;
    if(query&&!normalize([tool.title,tool.description,tool.subject,tool.tags.join(" ")].join(" ")).includes(query))return false;
    if(values.grade&&tool.grade!==values.grade)return false;if(values.term&&tool.term!=="전 학기"&&tool.term!==values.term)return false;if(values.subject&&tool.subject!==values.subject)return false;if(values.minutes&&tool.minutes>Number(values.minutes))return false;if(values.difficulty&&tool.difficulty!==values.difficulty)return false;if(values.group&&tool.group!==values.group)return false;if(values.device&&tool.device!==values.device)return false;if(values.runtime&&!tool.runtime.includes(values.runtime))return false;return true;
  });
  if(state.view==="recent")state.filtered.sort((a,b)=>recentOrder.get(a.id)-recentOrder.get(b.id));renderCatalog();
}
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function renderCatalog(){const list=$("[data-catalog-list]");const favorites=new Set(read(KEYS.favorites,[]));list.replaceChildren(...state.filtered.map(tool=>{const card=el("article","catalog-card");const fav=el("button","favorite",favorites.has(tool.id)?"★":"☆");fav.type="button";fav.dataset.favorite=tool.id;fav.setAttribute("aria-label",`${tool.title} 즐겨찾기`);card.append(fav,el("h3","",tool.title));const chips=el("div","chips");[tool.grade,tool.term,tool.subject,`${tool.minutes}분`,tool.difficulty,tool.group,tool.device].forEach(value=>chips.append(el("span","",value)));card.append(chips,el("p","",tool.description),el("p","curriculum-note",`핵심 개념: ${tool.standard} · 선수 학습: ${tool.prerequisite}`));const actions=el("div","catalog-actions");const open=el("a","", "바로 열기 ↗");open.href=new URL(tool.path,rootPage).href;open.target="_blank";open.rel="noreferrer";const add=el("button","","수업에 담기");add.type="button";add.dataset.add=tool.id;actions.append(open,add);card.append(actions);return card}));$("[data-result-count]").textContent=`${state.filtered.length}개`;$("[data-catalog-empty]").hidden=state.filtered.length!==0}
function renderTray(){const list=$("[data-tray-list]");list.replaceChildren(...state.draft.map((item,index)=>{const li=el("li");li.append(el("strong","",`${index+1}. ${item.title}`));const controls=el("div","tray-controls");const minutes=document.createElement("input");minutes.type="number";minutes.min="1";minutes.max="180";minutes.value=item.minutes;minutes.setAttribute("aria-label",`${item.title} 활동 시간(분)`);minutes.dataset.minutes=index;const note=document.createElement("input");note.value=item.note||"";note.placeholder="교사 메모";note.setAttribute("aria-label",`${item.title} 교사 메모`);note.dataset.note=index;const up=el("button","","↑");up.type="button";up.dataset.move=`${index}:-1`;up.disabled=index===0;up.setAttribute("aria-label",`${item.title} 앞 순서로 이동`);const down=el("button","","↓");down.type="button";down.dataset.move=`${index}:1`;down.disabled=index===state.draft.length-1;down.setAttribute("aria-label",`${item.title} 뒤 순서로 이동`);const remove=el("button","","삭제");remove.type="button";remove.dataset.remove=index;controls.append(minutes,note,up,down,remove);li.append(controls);return li}));$("[data-tray-count]").textContent=state.draft.length;$("[data-tray-empty]").hidden=state.draft.length!==0}
function makePreset(name,items){return{schema:PRESET_SCHEMA,name:name||"이름 없는 수업",createdAt:new Date().toISOString(),items:items.map(item=>({toolId:item.toolId||item.id,title:item.title,path:item.path,minutes:Math.max(1,Number(item.minutes)||20),note:String(item.note||""),settings:item.settings&&typeof item.settings==="object"?item.settings:{query:""}}))}}
function validPreset(value){return value&&value.schema===PRESET_SCHEMA&&typeof value.name==="string"&&Array.isArray(value.items)&&value.items.length>0&&value.items.every(item=>typeof item.toolId==="string"&&typeof item.path==="string")}
function renderPlaylists(){const list=$("[data-saved-list]");list.replaceChildren(...state.playlists.map((preset,index)=>{const card=el("article","saved-card");card.append(el("h3","",preset.name),el("p","",`${preset.items.length}개 도구 · 약 ${preset.items.reduce((sum,item)=>sum+Number(item.minutes||0),0)}분`));const row=el("div","button-row");[["수업 시작","start"],["공유·내보내기","share"],["편집","edit"],["삭제","delete"]].forEach(([label,action])=>{const button=el("button",action==="delete"?"danger":"",label);button.type="button";button.dataset.playlistAction=action;button.dataset.playlistIndex=index;row.append(button)});card.append(row);return card}));$("[data-saved-empty]").hidden=state.playlists.length!==0;save(KEYS.playlists,state.playlists)}
function startLesson(preset){state.active=preset;state.activeIndex=0;$("[data-lesson]").hidden=false;document.body.style.overflow="hidden";loadLessonItem()}
function loadLessonItem(){const item=state.active.items[state.activeIndex];const url=new URL(item.path,rootPage);const query=item.settings?.query;if(query)url.search=query.startsWith("?")?query:`?${query}`;$("[data-lesson-frame]").src=url.href;$("[data-lesson-new]").href=url.href;$("[data-lesson-title]").textContent=item.title;$("[data-lesson-progress]").textContent=`${state.activeIndex+1} / ${state.active.items.length}${item.note?` · ${item.note}`:""}`;$("[data-lesson-prev]").disabled=state.activeIndex===0;$("[data-lesson-next]").disabled=state.activeIndex===state.active.items.length-1;state.seconds=Math.round(Number(item.minutes||20)*60);state.running=false;updateTimer()}
function updateTimer(){const min=Math.floor(state.seconds/60);const sec=Math.max(0,state.seconds%60);$("[data-timer]").textContent=`${String(min).padStart(2,"0")}:${String(sec).padStart(2,"0")}`;$("[data-timer-toggle]").textContent=state.running?"일시정지":"시작";if(state.seconds<=0){state.running=false;clearInterval(state.timerId);$("[data-timer]").textContent="시간 끝"}}
function toggleTimer(){state.running=!state.running;clearInterval(state.timerId);if(state.running)state.timerId=setInterval(()=>{state.seconds-=1;updateTimer()},1000);updateTimer()}
function encodePreset(preset){const bytes=new TextEncoder().encode(JSON.stringify(preset));let binary="";bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function decodePreset(value){const base=value.replace(/-/g,"+").replace(/_/g,"/");const binary=atob(base);return JSON.parse(new TextDecoder().decode(Uint8Array.from(binary,char=>char.charCodeAt(0))))}
function sharePreset(preset){state.sharePreset=preset;const url=new URL(location.href);url.hash=`preset=${encodePreset(preset)}`;$("[data-share-url]").value=url.href;const qr=$("#share-qr");qr.replaceChildren();new QRCode(qr,{text:url.href,width:220,height:220,colorDark:"#111c35",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.M});$("[data-share-dialog]").showModal()}
function downloadJson(preset){const blob=new Blob([JSON.stringify(preset,null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${preset.name.replace(/[^\p{L}\p{N}_-]+/gu,"-")||"math-class"}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
function importFromHash(){if(!location.hash.startsWith("#preset="))return;try{const preset=decodePreset(location.hash.slice(8));if(!validPreset(preset))throw new Error();state.playlists.unshift(preset);renderPlaylists();history.replaceState({},"",location.pathname+location.search);alert(`‘${preset.name}’ 수업을 보관함에 가져왔습니다.`)}catch{alert("공유 프리셋 링크를 읽지 못했습니다.")}}

document.addEventListener("input",event=>{if(event.target.matches("[data-search],[data-filter]"))applyFilters();if(event.target.dataset.minutes!==undefined)state.draft[Number(event.target.dataset.minutes)].minutes=Math.max(1,Number(event.target.value)||1);if(event.target.dataset.note!==undefined)state.draft[Number(event.target.dataset.note)].note=event.target.value});
document.addEventListener("change",event=>{if(event.target.matches("[data-filter]"))applyFilters()});
document.addEventListener("click",async event=>{
  const target=event.target.closest("button,[data-playlist-action]");if(!target)return;
  if(target.dataset.view){state.view=target.dataset.view;document.querySelectorAll("[data-view]").forEach(button=>button.classList.toggle("active",button===target));applyFilters()}
  if(target.dataset.favorite){const values=new Set(read(KEYS.favorites,[]));values.has(target.dataset.favorite)?values.delete(target.dataset.favorite):values.add(target.dataset.favorite);save(KEYS.favorites,[...values]);applyFilters()}
  if(target.dataset.add){const tool=state.tools.find(item=>item.id===target.dataset.add);if(tool&&!state.draft.some(item=>item.id===tool.id)){state.draft.push({...tool,note:""});renderTray()}}
  if(target.dataset.remove!==undefined){state.draft.splice(Number(target.dataset.remove),1);renderTray()}
  if(target.dataset.move){const [from,delta]=target.dataset.move.split(":").map(Number);const [item]=state.draft.splice(from,1);state.draft.splice(from+delta,0,item);renderTray()}
  if(target.matches("[data-clear-tray]")){state.draft=[];renderTray()}
  if(target.matches("[data-reset-filters]")){$("[data-search]").value="";document.querySelectorAll("[data-filter]").forEach(select=>select.value="");applyFilters()}
  if(target.matches("[data-save-playlist]")){if(!state.draft.length)return alert("수업에 도구를 먼저 담아 주세요.");const preset=makePreset($("[data-playlist-name]").value,state.draft);state.playlists.unshift(preset);state.draft=[];$("[data-playlist-name]").value="";renderTray();renderPlaylists()}
  if(target.dataset.playlistAction){const index=Number(target.dataset.playlistIndex),preset=state.playlists[index],action=target.dataset.playlistAction;if(action==="start")startLesson(preset);if(action==="share")sharePreset(preset);if(action==="edit"){state.draft=preset.items.map(item=>({...item,id:item.toolId}));$("[data-playlist-name]").value=preset.name;renderTray();scrollTo({top:0,behavior:"smooth"})}if(action==="delete"&&confirm(`‘${preset.name}’ 수업을 삭제할까요?`)){state.playlists.splice(index,1);renderPlaylists()}}
  if(target.matches("[data-copy-share]")){await navigator.clipboard.writeText($("[data-share-url]").value);target.textContent="복사됨";setTimeout(()=>target.textContent="링크 복사",1200)}
  if(target.matches("[data-download-preset]"))downloadJson(state.sharePreset);
  if(target.matches("[data-lesson-prev]")){state.activeIndex-=1;loadLessonItem()}if(target.matches("[data-lesson-next]")){state.activeIndex+=1;loadLessonItem()}if(target.matches("[data-lesson-reload]"))$("[data-lesson-frame]").contentWindow.location.reload();if(target.matches("[data-lesson-fullscreen]"))$("[data-lesson]").requestFullscreen?.();if(target.matches("[data-lesson-close]")){clearInterval(state.timerId);$("[data-lesson]").hidden=true;$("[data-lesson-frame]").src="about:blank";document.body.style.overflow=""}if(target.matches("[data-timer-toggle]"))toggleTimer();if(target.matches("[data-timer-reset]")){state.seconds=Math.round(Number(state.active.items[state.activeIndex].minutes||20)*60);state.running=false;clearInterval(state.timerId);updateTimer()}
});
$("[data-preset-file]").addEventListener("change",async event=>{try{const preset=JSON.parse(await event.target.files[0].text());if(!validPreset(preset))throw new Error();state.playlists.unshift(preset);renderPlaylists()}catch{alert("math-class-preset/v1 형식의 JSON 파일이 아닙니다.")}event.target.value=""});
renderTray();renderPlaylists();loadCatalog();
