(() => {"use strict"; const M=window.TurtleMath,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ids=["sequence","startX","startY","heading","angle","clockwise","repeats","scale","speed","color","width","dots","grid","axes","autofit","colorRule","symmetry","background"];
const state={path:null,analysis:null,visible:0,playing:false,timer:null,attempts:0,score:0,startTime:Date.now(),mission:0};
const missions=[
 {title:"제시 숫자열로 완성",hint:"3, 5, 2, 1, 6을 90°씩 돌려 8번 반복하세요.",config:{sequence:[3,5,2,1,6],angle:90,repeats:8},type:"closed",points:10},
 {title:"그림과 숫자열 연결",hint:"정사각형 경로가 되는 숫자열과 90° 회전의 관계를 설명하세요.",config:{sequence:[3,3,3,3],angle:90,repeats:1},type:"closed",points:10},
 {title:"목표 끝점의 마지막 수",hint:"2, 3, 4 다음에 어떤 수를 놓아야 시작점에 닿을까요?",config:{sequence:[2,3,4,3],angle:90,repeats:1},type:"closed",points:15},
 {title:"시작점과 끝점 만나기",hint:"숫자열의 마지막 수를 편집해 닫힌 경로를 만드세요.",config:{sequence:[5,2,5,2],angle:90,repeats:1},type:"closed",points:15},
 {title:"회전각으로 목표 패턴",hint:"1~9를 세 번 반복해 닫히는 회전 패턴을 만드세요.",config:{sequence:[1,2,3,4,5,6,7,8,9],angle:120,repeats:3},type:"closed",points:20},
 {title:"변신 곱셈표의 단 추론",hint:"8단 디지털 루트 행을 보내 80° 패턴을 관찰하세요.",config:{sequence:M.multiplicationRow(8),angle:80,repeats:10},type:"closed",points:20}
];
function commandOrder(){return $("#blockList [data-command]")?.dataset.command==="turn"?"turn-move":"move-turn"}
function cfg(){return{sequence:$("#sequence").value,startX:+$("#startX").value,startY:+$("#startY").value,heading:+$("#heading").value,angle:+$("#angle").value,clockwise:$("#clockwise").value==="true",repeats:+$("#repeats").value,scale:+$("#scale").value,commandOrder:commandOrder()};}
function fmt(n){return Number(n).toFixed(Math.abs(n-Math.round(n))<1e-7?0:2)} function pt(p){return `(${fmt(p.x)}, ${fmt(p.y)})`}
function rebuild(resetVisible=true){try{state.path=M.buildPath(cfg());state.analysis=M.analyze(state.path);if(resetVisible)state.visible=0;$("#error").textContent="";renderChips();renderTable();renderAnalysis();render();$("#blockRepeat").textContent=state.path.repeats;$("#blockOrderNote").textContent=`현재 실행: ${state.path.commandOrder==="turn-move"?"회전 → 이동":"이동 → 회전"}`;}catch(e){state.path=null;$("#error").textContent=e.message;stop();}}
function el(name,attrs={}){const n=document.createElementNS("http://www.w3.org/2000/svg",name);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n}
function bounds(){if(!state.path)return[-20,-20,40,40];const b=state.analysis.bounds,pad=Math.max(2,Math.max(b.maxX-b.minX,b.maxY-b.minY)*.1),w=Math.max(8,b.maxX-b.minX+2*pad),h=Math.max(8,b.maxY-b.minY+2*pad);return[b.minX-pad,-b.maxY-pad,w,h]}
function render(){if(!state.path)return;const svg=$("#canvas"),b=$("#autofit").checked?bounds():[-20,-20,40,40];svg.setAttribute("viewBox",b.join(" "));svg.style.background=$("#background").value;const [gx,ax,pl,dl,tl]=["#gridLayer","#axesLayer","#pathLayer","#dotLayer","#turtleLayer"].map($);[gx,ax,pl,dl,tl].forEach(x=>x.replaceChildren());
 if($("#grid").checked){const step=Math.max(1,Math.ceil(Math.max(b[2],b[3])/30));for(let x=Math.floor(b[0]/step)*step;x<=b[0]+b[2];x+=step)gx.append(el("line",{x1:x,y1:b[1],x2:x,y2:b[1]+b[3],stroke:"#e8e4da","stroke-width":.035*b[2]}));for(let y=Math.floor(b[1]/step)*step;y<=b[1]+b[3];y+=step)gx.append(el("line",{x1:b[0],y1:y,x2:b[0]+b[2],y2:y,stroke:"#e8e4da","stroke-width":.035*b[2]}));}
 if($("#axes").checked){ax.append(el("line",{x1:b[0],y1:0,x2:b[0]+b[2],y2:0,stroke:"#758098","stroke-width":.06*b[2]}));ax.append(el("line",{x1:0,y1:b[1],x2:0,y2:b[1]+b[3],stroke:"#758098","stroke-width":.06*b[2]}));}
 const sym=+$("#symmetry").value,rule=$("#colorRule").value,colors=["#ef5b3f","#087f77","#5f6caf","#d49b00","#a64270","#168aad"];
 for(let copy=0;copy<sym;copy++){const g=el("g",{transform:`rotate(${copy*360/sym})`});for(let i=0;i<state.visible;i++){const s=state.path.steps[i],c=rule==="single"?$("#color").value:rule==="repeat"?colors[Math.floor(i/state.path.sequence.length)%colors.length]:rule==="gradient"?`hsl(${20+i/Math.max(1,state.path.steps.length)*300} 75% 48%)`:colors[i%colors.length];g.append(el("line",{x1:s.before.x,y1:-s.before.y,x2:s.after.x,y2:-s.after.y,stroke:c,"stroke-width":+$("#width").value*.07,"stroke-linecap":"round"}));}pl.append(g)}
 if($("#dots").checked)state.path.points.slice(0,state.visible+1).forEach((p,i)=>dl.append(el("circle",{cx:p.x,cy:-p.y,r:.11*b[2],fill:i===state.visible?"#17233b":"#fff",stroke:"#17233b","stroke-width":.025*b[2]})));
 const cur=state.visible?state.path.steps[state.visible-1].after:{...state.path.start,heading:+$("#heading").value};const tg=el("g",{transform:`translate(${cur.x} ${-cur.y}) rotate(${-cur.heading})`});tg.append(el("path",{d:"M .7 0 L -.55 -.48 L -.32 0 L -.55 .48 Z",fill:"#ffd166",stroke:"#17233b","stroke-width":.12}));tl.append(tg);$("#stepBadge").textContent=`${state.visible} / ${state.path.steps.length} 단계`;
 const s=state.visible?state.path.steps[state.visible-1]:null;$("#now").textContent=s?`${s.index}단계 · 수 ${s.value} · ${pt(s.before)} → ${pt(s.after)} · 방향 ${fmt(s.after.heading)}°`:"준비: 규칙을 정하고 실행하세요.";$$('#stepRows tr').forEach((r,i)=>r.classList.toggle("current",i===state.visible-1));}
function renderTable(){const rows=state.path.steps.map(s=>`<tr><td>${s.index}</td><td><b>${s.value}</b></td><td>${pt(s.before)} · ${fmt(s.before.heading)}°</td><td>${pt(s.after)}</td><td>${fmt(s.after.heading)}°</td></tr>`).join("");$("#stepRows").innerHTML=rows;}
function renderAnalysis(){const a=state.analysis,b=a.bounds,items=[["한 주기 위치 변화",`${fmt(a.cycleDelta.x)}, ${fmt(a.cycleDelta.y)}`],["한 주기 방향 변화",`${fmt(a.cycleDelta.heading)}°`],["최초 닫힘",a.closedAt?`${a.closedAt}단계`:"찾지 못함"],["방향 주기",a.directionPeriod?`${a.directionPeriod}회`:"비정수 주기"],["서로 다른 점",a.uniquePoints],["선분 / 반복",`${a.segments} / ${a.repeatedSegments}`],["경계 상자",`${fmt(b.maxX-b.minX)} × ${fmt(b.maxY-b.minY)}`],["총 이동거리",fmt(a.totalDistance)]];$("#metrics").innerHTML=items.map(x=>`<div class="metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join("");$("#question").textContent=a.repeatedSegments?"같은 선분이 반복됩니다. 회전대칭의 중심과 최소 회전각을 그림에서 찾아볼까요?":"대칭이나 회전대칭처럼 보이나요? 자동 판정보다 대응하는 점과 선분을 직접 근거로 확인해 보세요.";}
function renderChips(){if(!state.path)return;$("#chips").innerHTML=state.path.sequence.map((n,i)=>`<button class="chip" draggable="true" data-i="${i}" aria-label="숫자 ${n}, ${i+1}번째">${n}</button>`).join("");let from=null;$$('.chip').forEach(c=>{c.ondragstart=()=>{from=+c.dataset.i;c.classList.add('dragging')};c.ondragend=()=>c.classList.remove('dragging');c.ondragover=e=>e.preventDefault();c.ondrop=()=>{const a=[...state.path.sequence],to=+c.dataset.i,[v]=a.splice(from,1);a.splice(to,0,v);$("#sequence").value=a.join(", ");rebuild();}})}
function stop(){state.playing=false;clearInterval(state.timer);$("#play").textContent="재생"} function play(){if(!state.path)return;if(state.playing){stop();return}if(state.visible>=state.path.steps.length)state.visible=0;state.playing=true;$("#play").textContent="일시정지";state.timer=setInterval(()=>{if(++state.visible>=state.path.steps.length)stop();render()},Math.max(60,900-+$("#speed").value*80));}
function applyConfig(c){$("#sequence").value=c.sequence.join(", ");["startX","startY","heading","angle","repeats","scale"].forEach(k=>{if(c[k]!=null)$("#"+k).value=c[k]});if(c.commandOrder==="turn-move")$("#blockList").prepend($("#blockList [data-command=turn]"));rebuild()}
function renderMissions(){$("#missionList").innerHTML=missions.map((m,i)=>`<button class="${i===state.mission?'active':''}" data-m="${i}"><b>${i+1}. ${m.title}</b><br><small>${m.hint}</small></button>`).join("");$$('[data-m]').forEach(b=>b.onclick=()=>{state.mission=+b.dataset.m;applyConfig({...cfg(),...missions[state.mission].config});renderMissions()})}
function table(){for(let i=1;i<=9;i++)$("#dan").insertAdjacentHTML("beforeend",`<option>${i}</option>`);function draw(){const d=+$("#dan").value;$("#timesTable").innerHTML=M.multiplicationRow(d).map((r,i)=>`<button data-product="${d*(i+1)}">${d}×${i+1}=${d*(i+1)}<b>→ ${r}</b></button>`).join("");$$('[data-product]').forEach(b=>b.onclick=()=>{const n=+b.dataset.product,steps=M.digitalRootSteps(n);$("#rootCalc").textContent=`${d}×${n/d}=${n}`+(steps.length>1?" → "+steps.slice(1).map((v,i)=>`${String(steps[i]).split('').join('+')}=${v}`).join(" → "):" → 이미 한 자리")});}$("#dan").onchange=draw;draw();$("#sendRow").onclick=()=>{$("#sequence").value=M.multiplicationRow(+$("#dan").value).join(", ");rebuild();$("[data-tab=lab]").click()}}
function download(name,text,type){const a=document.createElement("a"),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function svgText(){const clone=$("#canvas").cloneNode(true);clone.setAttribute("xmlns","http://www.w3.org/2000/svg");return new XMLSerializer().serializeToString(clone)}
ids.forEach(id=>$("#"+id)?.addEventListener("input",()=>rebuild(id!=="color"&&id!=="width"&&id!=="background"&&id!=="colorRule"&&id!=="symmetry")));$("#drawAll").onclick=()=>{state.visible=state.path?.steps.length||0;render()};$("#play").onclick=play;$("#step").onclick=()=>{if(state.path){stop();state.visible=Math.min(state.path.steps.length,state.visible+1);render()}};$("#undo").onclick=()=>{stop();state.visible=Math.max(0,state.visible-1);render()};$("#reset").onclick=()=>{stop();state.visible=0;render()};
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-pane]').forEach(p=>p.hidden=p.dataset.pane!==b.dataset.tab)});$("#guideButton").onclick=()=>$("#guide").showModal();$("#closeGuide").onclick=()=>$("#guide").close();$("#printBtn").onclick=()=>print();$("#fullscreen").onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
$("#judge").onclick=()=>{state.attempts++;const m=missions[state.mission],r=M.judgeMission(state.path,{type:m.type});if(r.pass)state.score+=m.points;$("#attempts").textContent=state.attempts;$("#score").textContent=state.score;$("#missionFeedback").textContent=r.message};
$$('.block-up,.block-down').forEach(button=>button.onclick=()=>{const item=button.closest('[data-command]'),other=$$("#blockList [data-command]").find(x=>x!==item);if(!other)return;if(button.classList.contains('block-up'))$("#blockList").insertBefore(item,other);else $("#blockList").insertBefore(other,item);rebuild();});
$("#exportSvg").onclick=()=>download("숫자도형.svg",svgText(),"image/svg+xml");$("#exportPng").onclick=()=>{const img=new Image(),svg=svgText(),u=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));img.onload=()=>{const c=document.createElement("canvas");c.width=1600;c.height=1200;const x=c.getContext("2d");x.fillStyle=$("#background").value;x.fillRect(0,0,c.width,c.height);x.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(u);c.toBlob(blob=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="숫자도형.png";a.click()},"image/png")};img.src=u};
function preset(){return{kind:"number-turtle-lab",version:1,config:cfg(),mission:{title:$("#teacherTitle").value,hint:$("#teacherHint").value,timeLimit:+$("#timeLimit").value,type:$("#judgeType").value,x:+$("#targetX").value,y:+$("#targetY").value},notes:$("#artNote").value}}$("#saveJson").onclick=()=>download("숫자도형-프리셋.json",JSON.stringify(preset(),null,2),"application/json");$("#loadJson").onclick=()=>$("#jsonFile").click();$("#jsonFile").onchange=async e=>{try{const p=M.validatePreset(JSON.parse(await e.target.files[0].text()));applyConfig(p.config);$("#teacherTitle").value=p.mission.title||"";$("#teacherHint").value=p.mission.hint||"";$("#error").textContent="프리셋을 불러왔습니다."}catch(err){$("#error").textContent=`불러오기 실패: ${err.message}`}};
setInterval(()=>{const s=Math.floor((Date.now()-state.startTime)/1000);$("#timer").textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`},1000);table();renderMissions();rebuild();if(new URLSearchParams(location.search).has("manual"))$("#guide").showModal();})();
