const palettes={garden:['#f4b43f','#e9654b','#4b9d83','#f6e8c4'],ocean:['#0d6380','#36a6a1','#9ed9c5','#f2cf75'],berry:['#6a376f','#bc4b70','#ef8d76','#f7d9c4'],mono:['#26332e','#66756e','#b6c0bb','#eef1ed']};
const modes={
  translation:{name:'잘라서 반대편으로 평행이동',icon:'→',caption:'모든 조각이 같은 방향으로 평행이동합니다.'},
  halfturn:{name:'이웃 조각을 180° 반회전',icon:'↻',caption:'같은 조각이 한 칸마다 180° 돌아가며 맞물립니다.'},
  triangle:{name:'한 변을 기준으로 대칭이동',icon:'◩',caption:'삼각형이 변을 사이에 두고 거울처럼 반사됩니다.'},
  hexagon:{name:'꼭짓점 둘레로 60° 회전',icon:'⬡',caption:'육각형 세 개의 120° 내각이 한 점에서 만납니다.'},
  glide:{name:'반사한 뒤 옆으로 평행이동',icon:'⌁',caption:'위아래 조각이 뒤집힌 채 반 칸씩 미끄러집니다.'},
  diamond:{name:'두 방향으로 평행이동',icon:'◇',caption:'마름모의 마주 보는 변이 각각 평행이동으로 연결됩니다.'}
};
const constructionMethods={
  translate:{title:'평행이동',hint:'왼쪽에서 잘라 낸 조각을 방향을 바꾸지 않고 같은 높이의 오른쪽 변에 붙입니다.',mode:'translation'},
  rotate:{title:'180° 반회전',hint:'한 변의 절반에서 잘라 낸 조각을 변의 중점 둘레로 180° 돌려 같은 변의 다른 절반에 붙입니다.',mode:'halfturn'},
  glide:{title:'미끄럼 반사',hint:'잘라 낸 조각을 거울처럼 뒤집은 다음 기준선과 나란히 옆으로 옮겨 붙입니다.',mode:'glide'}
};
function methodForMode(mode){if(mode==='glide')return 'glide';if(mode==='halfturn'||mode==='triangle'||mode==='hexagon')return 'rotate';return 'translate'}
const examples={
  fish:{mode:'translation',amplitude:38,waves:1,skew:12,palette:'ocean',density:7},bird:{mode:'halfturn',amplitude:31,waves:2,skew:-18,palette:'garden',density:6},
  mountain:{mode:'triangle',amplitude:24,waves:2,skew:20,palette:'berry',density:8},honey:{mode:'hexagon',amplitude:8,waves:1,skew:0,palette:'garden',density:7},
  wave:{mode:'glide',amplitude:34,waves:3,skew:-10,palette:'ocean',density:8},leaf:{mode:'diamond',amplitude:27,waves:2,skew:24,palette:'garden',density:7},
  pinwheel:{mode:'halfturn',amplitude:43,waves:1,skew:30,palette:'berry',density:6},ice:{mode:'hexagon',amplitude:18,waves:3,skew:-14,palette:'ocean',density:9}
};
const state={mode:'translation',method:'translate',amplitude:28,waves:2,skew:0,palette:'garden',density:7,outline:true,guides:false,history:[],drag:null};
const editor=document.querySelector('[data-editor-canvas]'),preview=document.querySelector('[data-preview-canvas]'),hero=document.querySelector('[data-hero-canvas]');
const toast=document.querySelector('[data-toast]');let toastTimer;
function showToast(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1800)}
function fitCanvas(canvas){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);const w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return {ctx,w:rect.width,h:rect.height}}
function wave(t,amp,waves,phase=0){return amp*(Math.sin(Math.PI*t)*.7+Math.sin(Math.PI*2*waves*t+phase)*.3*Math.sin(Math.PI*t))}
function tilePath(ctx,size,mode,amp=state.amplitude,waves=state.waves,skew=state.skew){const n=18,a=amp/100*size*.46,s=skew/100*size*.2;ctx.beginPath();
  if(mode==='triangle'){const height=size*(.56+amp/220),apex=skew/35*size*.28;ctx.moveTo(-size*.5,height*.35);ctx.lineTo(size*.5,height*.35);ctx.lineTo(apex,-height*.65);ctx.closePath();return}
  if(mode==='hexagon'){const rx=size*.48,ry=size*(.35+amp/420),shear=skew/160;for(let i=0;i<6;i++){const ang=Math.PI/3*i-Math.PI/6,y=Math.sin(ang)*ry,x=Math.cos(ang)*rx+y*shear;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.closePath();return}
  if(mode==='diamond'){ctx.moveTo(-size*.52,0);ctx.lineTo(s,-size*.42);ctx.lineTo(size*.52,0);ctx.lineTo(-s,size*.42);ctx.closePath();return}
  const half=size*.48;
  const edgeWave=(t,amount,phase)=>mode==='halfturn'?amount*Math.sin(Math.PI*2*waves*t):mode==='glide'?amount*Math.sin(Math.PI*t):wave(t,amount,waves,phase);
  ctx.moveTo(-half+s,-half);
  for(let i=1;i<=n;i++){const t=i/n;ctx.lineTo(-half+s+size*.96*t,-half+edgeWave(t,a,.4))}
  for(let i=1;i<=n;i++){const t=i/n;ctx.lineTo(half+s-2*s*t+edgeWave(t,a*.85,1.1),-half+size*.96*t)}
  for(let i=n-1;i>=0;i--){const t=i/n;ctx.lineTo(-half-s+size*.96*t,half+edgeWave(t,a,.4))}
  for(let i=n-1;i>=0;i--){const t=i/n;ctx.lineTo(-half+s-2*s*t+edgeWave(t,a*.85,1.1),-half+size*.96*t)}ctx.closePath();
}
function decorate(ctx,size,index,mode){ctx.save();ctx.globalAlpha=.2;ctx.strokeStyle='#173b32';ctx.lineWidth=Math.max(1,size*.025);ctx.beginPath();if(mode==='hexagon'){ctx.arc(0,0,size*.18,0,Math.PI*2)}else if(mode==='triangle'){ctx.moveTo(-size*.18,size*.18);ctx.lineTo(0,-size*.16);ctx.lineTo(size*.18,size*.18)}else{ctx.moveTo(-size*.22,0);ctx.quadraticCurveTo(0,(index%2?-.18:.18)*size,size*.22,0)}ctx.stroke();ctx.restore()}
function tileMetrics(mode,size,amp=state.amplitude){if(mode==='triangle')return {dx:size,dy:size*.84};if(mode==='hexagon')return {dx:size*.48*Math.sqrt(3),dy:size*(.35+amp/420)*1.5};if(mode==='diamond')return {dx:size*1.04,dy:size*.84};return {dx:size*.96,dy:size*.96}}
function drawPattern(canvas,custom={}){const {ctx,w,h}=fitCanvas(canvas);const mode=custom.mode||state.mode,colors=palettes[custom.palette||state.palette],density=custom.density||state.density,amp=custom.amplitude??state.amplitude,skew=custom.skew??state.skew;ctx.clearRect(0,0,w,h);ctx.fillStyle=custom.background||'#173f35';ctx.fillRect(0,0,w,h);const size=Math.max(35,w/density),m=tileMetrics(mode,size,amp);let idx=0;
  if(mode==='triangle'){const amp=custom.amplitude??state.amplitude,skew=custom.skew??state.skew,cellH=size*(.56+amp/220),apex=size*.5+skew/35*size*.28;for(let row=-2;row<h/cellH+2;row++)for(let col=-2;col<w/size+2;col++){const x=col*size+row*(apex-size*.5),y=row*cellH;const triangles=[[[x,y],[x+size,y],[x+apex,y+cellH]],[[x+size,y],[x+size+apex,y+cellH],[x+apex,y+cellH]]];triangles.forEach((pts,j)=>{ctx.beginPath();ctx.moveTo(...pts[0]);ctx.lineTo(...pts[1]);ctx.lineTo(...pts[2]);ctx.closePath();ctx.fillStyle=colors[Math.abs(col+row*2+j)%colors.length];ctx.fill();if(custom.outline??state.outline){ctx.strokeStyle='rgba(20,45,38,.58)';ctx.lineWidth=Math.max(.7,size*.018);ctx.stroke()}})}return}
  if(mode==='diamond'){const width=size*1.04,height=size*.84,s=skew/100*size*.2,v1={x:width/2-s,y:height/2},v2={x:width/2+s,y:-height/2},range=Math.ceil((w+h)/Math.min(width,height))+4;for(let i=-range;i<=range;i++)for(let j=-range;j<=range;j++){const x=w/2+i*v1.x+j*v2.x,y=h/2+i*v1.y+j*v2.y;if(x<-width||x>w+width||y<-height||y>h+height)continue;ctx.save();ctx.translate(x,y);tilePath(ctx,size,mode,amp,custom.waves??state.waves,skew);ctx.fillStyle=colors[Math.abs(i+2*j)%colors.length];ctx.fill();if(custom.outline??state.outline){ctx.strokeStyle='rgba(20,45,38,.58)';ctx.lineWidth=Math.max(.7,size*.018);ctx.stroke()}decorate(ctx,size,idx++,mode);ctx.restore()}return}
  for(let row=-2;row<h/m.dy+3;row++)for(let col=-2;col<w/m.dx+3;col++){let x=col*m.dx,y=row*m.dy;if(mode==='translation'||mode==='halfturn')x-=row*2*(skew/100*size*.2);if(mode==='hexagon'&&row%2)x+=m.dx/2;if(mode==='hexagon')x+=row*m.dy*skew/160;ctx.save();ctx.translate(x,y);if(mode==='halfturn'&&(col+row)%2)ctx.rotate(Math.PI);if(mode==='glide'&&row%2)ctx.scale(-1,1);tilePath(ctx,size,mode,amp,custom.waves??state.waves,skew);ctx.fillStyle=colors[Math.abs(col+row*2)%colors.length];ctx.fill();if(custom.outline??state.outline){ctx.strokeStyle='rgba(20,45,38,.58)';ctx.lineWidth=Math.max(.7,size*.018);ctx.stroke()}decorate(ctx,size,idx++,mode);ctx.restore()}
}
function controlPoints(w,h){const size=Math.min(w,h)*.64,cx=w/2,cy=h/2,a=state.amplitude/48;return [{x:cx,y:cy-size/2+a*size*.22,type:'amplitude'},{x:cx+size/2+a*size*.19,y:cy,type:'side'},{x:cx+state.skew/35*size*.28,y:cy+size*.36,type:'skew'}]}
function drawConstructionOverlay(ctx,w,h,size){const cx=w/2,cy=h/2,half=size*.48;ctx.save();ctx.lineWidth=2;ctx.font='700 9px Noto Sans KR';ctx.textAlign='center';ctx.setLineDash([6,5]);ctx.strokeStyle='#ef8b3c';ctx.fillStyle='rgba(239,139,60,.2)';
  function marker(x,y,target=false){ctx.beginPath();ctx.ellipse(x,y,13,24,0,0,Math.PI*2);ctx.fillStyle=target?'rgba(30,114,92,.22)':'rgba(239,139,60,.22)';ctx.fill();ctx.strokeStyle=target?'#1e725c':'#ef8b3c';ctx.setLineDash(target?[]:[5,4]);ctx.stroke()}
  function arrowHead(x,y,angle){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.fillStyle='#ef8b3c';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(-10,-5);ctx.lineTo(-10,5);ctx.closePath();ctx.fill();ctx.restore()}
  if(state.method==='translate'){marker(cx-half,cy);marker(cx+half,cy,true);ctx.strokeStyle='#ef8b3c';ctx.setLineDash([6,5]);ctx.beginPath();ctx.moveTo(cx-half-5,cy-42);ctx.bezierCurveTo(cx-size*.2,cy-88,cx+size*.2,cy-88,cx+half+5,cy-42);ctx.stroke();arrowHead(cx+half+5,cy-42,.7);ctx.fillStyle='#925017';ctx.fillText('방향 그대로 이동',cx,cy-92)}
  else if(state.method==='rotate'){marker(cx-half,cy-34);marker(cx-half,cy+34,true);ctx.strokeStyle='#ef8b3c';ctx.setLineDash([6,5]);ctx.beginPath();ctx.arc(cx-half-2,cy,48,-Math.PI/2,Math.PI/2,true);ctx.stroke();arrowHead(cx-half-2,cy+48,-.2);ctx.fillStyle='#925017';ctx.fillText('변의 중점 둘레로 180° 회전',cx,cy-half-70)}
  else{marker(cx-half,cy-24);marker(cx+half,cy+24,true);ctx.strokeStyle='#ef8b3c';ctx.setLineDash([6,5]);ctx.beginPath();ctx.moveTo(cx-half-4,cy-58);ctx.lineTo(cx+half+4,cy+58);ctx.stroke();arrowHead(cx+half+4,cy+58,.8);ctx.fillStyle='#925017';ctx.fillText('뒤집기 + 옆으로 이동',cx,cy-86)}ctx.restore()}
function drawEditor(){const {ctx,w,h}=fitCanvas(editor);ctx.clearRect(0,0,w,h);const size=Math.min(w,h)*.62;ctx.save();ctx.translate(w/2,h/2);ctx.shadowColor='rgba(31,60,48,.16)';ctx.shadowBlur=20;tilePath(ctx,size,state.mode);ctx.fillStyle=palettes[state.palette][0];ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#153c32';ctx.lineWidth=2;ctx.stroke();decorate(ctx,size,0,state.mode);ctx.restore();drawConstructionOverlay(ctx,w,h,size);const points=controlPoints(w,h);points.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,9,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.lineWidth=4;ctx.strokeStyle='#ef8b3c';ctx.stroke();ctx.fillStyle='#173f35';ctx.font='700 9px DM Mono';ctx.textAlign='center';ctx.fillText(String.fromCharCode(65+i),p.x,p.y-15)});ctx.fillStyle='#69746e';ctx.font='600 10px Noto Sans KR';ctx.fillText(state.mode==='hexagon'?'꼭짓점의 변화를 조절합니다':'주황색 홈과 초록색 돌기가 같은 모양으로 대응합니다',w/2,h-20)}
function syncUI(){document.querySelectorAll('[data-mode]').forEach(b=>{const on=b.dataset.mode===state.mode;b.classList.toggle('is-active',on);b.setAttribute('aria-checked',String(on))});document.querySelectorAll('[data-method]').forEach(b=>{const on=b.dataset.method===state.method;b.classList.toggle('is-active',on);b.setAttribute('aria-checked',String(on))});document.querySelectorAll('[data-palette]').forEach(b=>{const on=b.dataset.palette===state.palette;b.classList.toggle('is-active',on);b.setAttribute('aria-checked',String(on))});['amplitude','waves','skew','density'].forEach(key=>{const input=document.querySelector(`[data-control="${key}"]`),out=document.querySelector(`[data-output="${key}"]`);if(input)input.value=state[key];if(out)out.textContent=state[key]});const method=constructionMethods[state.method];document.querySelector('[data-method-hint]').innerHTML=`<b>${method.title}</b> ${method.hint}`;document.querySelector('[data-rule-name]').textContent=modes[state.mode].name;document.querySelector('[data-rule-icon]').textContent=modes[state.mode].icon;document.querySelector('[data-preview-caption]').textContent=modes[state.mode].caption;document.querySelector('[data-undo]').disabled=!state.history.length;document.querySelector('[data-transform-guide]').hidden=!state.guides}
function render(){syncUI();drawEditor();drawPattern(preview);drawPattern(hero,{mode:'translation',palette:'garden',density:8,amplitude:38,waves:1,skew:12,outline:true,background:'#173f35'})}
function snapshot(){state.history.push({mode:state.mode,method:state.method,amplitude:state.amplitude,waves:state.waves,skew:state.skew,palette:state.palette,density:state.density,outline:state.outline,guides:state.guides});if(state.history.length>30)state.history.shift()}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{snapshot();state.mode=b.dataset.mode;state.method=methodForMode(state.mode);render()}));
document.querySelectorAll('[data-method]').forEach(b=>b.addEventListener('click',()=>{snapshot();state.method=b.dataset.method;state.mode=constructionMethods[state.method].mode;render();showToast(`${constructionMethods[state.method].title} 방법을 적용했어요.`)}));
document.querySelectorAll('[data-palette]').forEach(b=>b.addEventListener('click',()=>{snapshot();state.palette=b.dataset.palette;render()}));
document.querySelectorAll('[data-control]').forEach(input=>{input.addEventListener('pointerdown',snapshot,{once:false});input.addEventListener('input',()=>{state[input.dataset.control]=Number(input.value);render()})});
document.querySelectorAll('[data-toggle]').forEach(input=>input.addEventListener('change',()=>{state[input.dataset.toggle]=input.checked;render()}));
document.querySelector('[data-randomize]').addEventListener('click',()=>{snapshot();const keys=Object.keys(modes);state.mode=keys[Math.floor(Math.random()*keys.length)];state.method=methodForMode(state.mode);state.amplitude=12+Math.floor(Math.random()*36);state.waves=1+Math.floor(Math.random()*3);state.skew=-30+Math.floor(Math.random()*61);render();showToast('새로운 조각을 만들었어요!')});
document.querySelector('[data-reset]').addEventListener('click',()=>{snapshot();Object.assign(state,{mode:'translation',method:'translate',amplitude:28,waves:2,skew:0,palette:'garden',density:7});render()});
document.querySelector('[data-undo]').addEventListener('click',()=>{const prev=state.history.pop();if(prev){Object.assign(state,prev);render()}});
function applyExample(name,scroll=true){const ex=examples[name];if(!ex)return;snapshot();Object.assign(state,ex);state.method=methodForMode(state.mode);render();if(scroll)document.querySelector('#studio').scrollIntoView({behavior:'smooth'});showToast('예시 조각을 편집기에 불러왔어요.')}
document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>applyExample(b.dataset.example)));
document.querySelectorAll('[data-load-example]').forEach(b=>b.addEventListener('click',()=>applyExample(b.dataset.loadExample)));
document.querySelectorAll('[data-method-use]').forEach(b=>b.addEventListener('click',()=>{snapshot();state.method=b.dataset.methodUse;state.mode=constructionMethods[state.method].mode;render();document.querySelector('#studio').scrollIntoView({behavior:'smooth'});showToast(`${constructionMethods[state.method].title} 제작 방법을 시작합니다.`)}));
document.querySelector('[data-fullscreen]').addEventListener('click',e=>{const card=document.querySelector('.preview-card');card.classList.toggle('is-fullscreen');e.currentTarget.textContent=card.classList.contains('is-fullscreen')?'닫기':'크게 보기';setTimeout(render,60)});
document.querySelector('[data-download]').addEventListener('click',()=>{const exportCanvas=document.createElement('canvas');Object.assign(exportCanvas.style,{width:'1600px',height:'1000px',position:'fixed',left:'-2000px',top:'0'});document.body.append(exportCanvas);drawPattern(exportCanvas);exportCanvas.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='나의-테셀레이션.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);exportCanvas.remove();showToast('테셀레이션을 PNG로 저장했어요.')},'image/png')});
function pointerPosition(e){const r=editor.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
editor.addEventListener('pointerdown',e=>{const p=pointerPosition(e),{w,h}=editor.getBoundingClientRect(),pts=controlPoints(w,h);const hit=pts.findIndex(q=>Math.hypot(q.x-p.x,q.y-p.y)<24);if(hit>=0){snapshot();state.drag=hit;editor.setPointerCapture(e.pointerId)}});
editor.addEventListener('pointermove',e=>{if(state.drag===null)return;const p=pointerPosition(e),r=editor.getBoundingClientRect(),size=Math.min(r.width,r.height)*.62;if(state.drag===0)state.amplitude=Math.max(0,Math.min(48,Math.round((p.y-(r.height/2-size/2))/(size*.22)*48)));else if(state.drag===1)state.amplitude=Math.max(0,Math.min(48,Math.round((p.x-(r.width/2+size/2))/(size*.19)*48)));else state.skew=Math.max(-35,Math.min(35,Math.round((p.x-r.width/2)/(size*.28)*35)));render()});
editor.addEventListener('pointerup',()=>state.drag=null);editor.addEventListener('pointercancel',()=>state.drag=null);
function renderExampleCards(){document.querySelectorAll('.example-card').forEach(card=>{const ex=examples[card.dataset.example];drawPattern(card.querySelector('canvas'),{...ex,outline:true,background:'#eed9a9'})})}
let resizeTimer;addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{render();renderExampleCards()},120)});
render();renderExampleCards();
