(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.ResponseModel=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
  const ACTIVITY_PREFIX="MRA1.";const RESPONSE_PREFIX="MRR1.";
  function utf8Encode(value){if(typeof Buffer!=="undefined")return Buffer.from(value,"utf8").toString("base64url");const bytes=new TextEncoder().encode(value);let binary="";bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
  function utf8Decode(value){if(typeof Buffer!=="undefined")return Buffer.from(value,"base64url").toString("utf8");const base=value.replace(/-/g,"+").replace(/_/g,"/");const binary=atob(base);return new TextDecoder().decode(Uint8Array.from(binary,char=>char.charCodeAt(0)))}
  function hash(value){let result=2166136261;for(const char of value){result^=char.charCodeAt(0);result=Math.imul(result,16777619)}return(result>>>0).toString(36)}
  function cleanText(value,max=500){return String(value??"").trim().slice(0,max)}
  function createActivity(input){const title=cleanText(input.title,80),question=cleanText(input.question,300),type=["choice","number","text"].includes(input.type)?input.type:"text";const options=type==="choice"?[...new Set((input.options||[]).map(item=>cleanText(item,100)).filter(Boolean))]:[];if(!title||!question)throw new Error("제목과 질문이 필요합니다.");if(type==="choice"&&options.length<2)throw new Error("선택지는 두 개 이상이어야 합니다.");const base={version:1,title,question,type,options};return{...base,id:hash(JSON.stringify(base))}}
  function encodeActivity(activity){return ACTIVITY_PREFIX+utf8Encode(JSON.stringify(activity))}
  function decodeActivity(code){if(!String(code).startsWith(ACTIVITY_PREFIX))throw new Error("활동 코드 형식이 아닙니다.");const value=JSON.parse(utf8Decode(String(code).slice(ACTIVITY_PREFIX.length)));return createActivity(value)}
  function createPacket(activity,answer,alias=""){const safeAlias=cleanText(alias,20)||`익명-${hash(String(Date.now())+Math.random()).slice(0,4)}`;let safeAnswer;if(activity.type==="number"){safeAnswer=Number(answer);if(!Number.isFinite(safeAnswer))throw new Error("유효한 수를 입력하세요.")}else{safeAnswer=cleanText(answer,500);if(!safeAnswer)throw new Error("응답을 입력하세요.");if(activity.type==="choice"&&!activity.options.includes(safeAnswer))throw new Error("활동에 없는 선택지입니다.")}return{schema:"math-class-response/v1",activityId:activity.id,activityTitle:activity.title,type:activity.type,alias:safeAlias,answer:safeAnswer,submittedAt:new Date().toISOString()}}
  function encodePacket(packet){return RESPONSE_PREFIX+utf8Encode(JSON.stringify(packet))}
  function decodePacket(code){if(!String(code).startsWith(RESPONSE_PREFIX))throw new Error("응답 패킷 형식이 아닙니다.");const value=JSON.parse(utf8Decode(String(code).slice(RESPONSE_PREFIX.length)));if(value?.schema!=="math-class-response/v1"||!value.activityId||!["choice","number","text"].includes(value.type))throw new Error("응답 패킷 내용이 올바르지 않습니다.");return value}
  function aggregate(packets){if(!packets.length)throw new Error("응답이 없습니다.");const activityId=packets[0].activityId,type=packets[0].type;if(packets.some(item=>item.activityId!==activityId))throw new Error("서로 다른 활동의 응답이 섞여 있습니다.");const unique=[];const seen=new Set();packets.forEach(item=>{const key=`${item.alias}|${item.submittedAt}|${JSON.stringify(item.answer)}`;if(!seen.has(key)){seen.add(key);unique.push(item)}});const result={activityId,title:unique[0].activityTitle,type,count:unique.length,packets:unique};if(type==="choice"){result.counts={};unique.forEach(item=>result.counts[item.answer]=(result.counts[item.answer]||0)+1)}if(type==="number"){const values=unique.map(item=>Number(item.answer)).filter(Number.isFinite).sort((a,b)=>a-b);result.values=values;result.mean=values.reduce((a,b)=>a+b,0)/values.length;result.min=values[0];result.max=values.at(-1);result.median=values.length%2?values[(values.length-1)/2]:(values[values.length/2-1]+values[values.length/2])/2}if(type==="text")result.responses=unique.map(item=>({alias:item.alias,text:String(item.answer)}));return result}
  function toCsv(result){const quote=value=>`"${String(value??"").replace(/"/g,'""')}"`;return["activity_id,activity_title,type,alias,answer,submitted_at",...result.packets.map(item=>[item.activityId,item.activityTitle,item.type,item.alias,item.answer,item.submittedAt].map(quote).join(","))].join("\r\n")}
  return{createActivity,encodeActivity,decodeActivity,createPacket,encodePacket,decodePacket,aggregate,toCsv};
});
