(()=>{const G=FoldGeometry,svg=document.querySelector('#paper'),NS='http://www.w3.org/2000/svg';const square=[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:1}];
const state={mode:'punch',folds:[],poly:square,punch:{x:.72,y:.5,r:.04},cut:null,unfoldSteps:0,selectCut:[],freePoints:[],freeMode:false,mission:null,hint:0,colors:{paper:'#fffaf0',pattern:'#ef7f4d',background:'#e5ddc9'}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1900)}function E(tag,attrs={}){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}function P(p){return{x:50+p.x*500,y:50+p.y*500}}function path(poly){return poly.map((p,i)=>`${i?'L':'M'} ${P(p).x} ${P(p).y}`).join(' ')+' Z'}
function allowed(){return $('#allowedLines').value.split(',').map(x=>x.trim())}function currentResults(){if(state.mode==='cut')return state.cut?G.unfoldSegments([{a:state.cut[0],b:state.cut[1]}],state.folds,state.unfoldSteps):[];return G.unfoldPoints(state.punch?[state.punch]:[],state.folds,state.unfoldSteps)}
function axisEnds(l){const pts=[];[[0,0,1,0],[1,0,1,1],[1,1,0,1],[0,1,0,0]].forEach(([x1,y1,x2,y2])=>{const a={x:x1,y:y1},b={x:x2,y:y2},d1=G.signed(a,l),d2=G.signed(b,l);if(Math.abs(d1)<G.EPS)pts.push(a);if(d1*d2<0){const t=d1/(d1-d2);pts.push({x:x1+(x2-x1)*t,y:y1+(y2-y1)*t})}});return pts.slice(0,2)}
function render(){svg.innerHTML='';svg.style.background=state.colors.background;const unfolded=state.unfoldSteps>0;svg.append(E('path',{d:path(unfolded?square:state.poly),fill:state.colors.paper,stroke:'#173f3a','stroke-width':3}));for(let i=0;i<5;i++){const n=.2*i+.2;svg.append(E('line',{x1:P({x:n,y:0}).x,y1:50,x2:P({x:n,y:1}).x,y2:550,stroke:'#b9ac91','stroke-width':1}));svg.append(E('line',{x1:50,y1:P({x:0,y:n}).y,x2:550,y2:P({x:1,y:n}).y,stroke:'#b9ac91','stroke-width':1}))}
state.folds.forEach((f,i)=>{const pts=axisEnds(f.line);if(pts.length===2){const a=P(pts[0]),b=P(pts[1]);svg.append(E('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:i===state.folds.length-state.unfoldSteps?'#356ab7':'#2c8d84','stroke-width':3,'stroke-dasharray':'9 7'}))}});
if(state.mission)state.mission.target.forEach(p=>{const q=P(p);svg.append(E('circle',{cx:q.x,cy:q.y,r:state.punch.r*500,fill:'none',stroke:'#7b6aa8','stroke-width':3,'stroke-dasharray':'7 5'}))});
const results=currentResults();if(state.mode==='cut'){results.forEach((s,i)=>{const a=P(s.a),b=P(s.b);svg.append(E('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,stroke:s.generation===state.unfoldSteps?'#356ab7':'#ef7f4d','stroke-width':8,'stroke-linecap':'round'}))});if(!state.cut&&state.selectCut.length) {const a=P(state.selectCut[0]);svg.append(E('circle',{cx:a.x,cy:a.y,r:8,fill:'#ef7f4d'}))}}else results.forEach((p,i)=>{const q=P(p),isNew=(p.sources||[]).includes('접기 '+(state.folds.length-state.unfoldSteps+1));svg.append(E('circle',{cx:q.x,cy:q.y,r:state.punch.r*500,fill:isNew?'#356ab7':state.colors.pattern,stroke:'#fff','stroke-width':3}));const t=E('text',{x:q.x,y:q.y+4,'text-anchor':'middle',fill:'#fff','font-size':12,'font-weight':800});t.textContent=i+1;svg.append(t)});
if(!unfolded&&state.mode!=='cut'&&state.punch){const q=P(state.punch);svg.append(E('circle',{cx:q.x,cy:q.y,r:state.punch.r*500,fill:state.colors.pattern,opacity:.9}))}updatePanel(results)}
function updatePanel(results){$('#foldCount').textContent=state.folds.length;$('#layers').textContent=2**state.folds.length;$('#expected').textContent=2**state.folds.length;$('#actual').textContent=results.length;$('#history').innerHTML=state.folds.length?state.folds.map((f,i)=>`<li>${i+1}. ${f.line.id} · ${f.keep>0?'+':'−'} 쪽 유지</li>`).join(''):'<li>아직 접지 않았습니다.</li>';let reason='접기를 시작하면 반사 관계를 분석합니다.';if(state.folds.length&&results.length===2**state.folds.length)reason=`${state.folds.length}개 대칭축을 역순으로 반사해 예상한 수와 같습니다.`;else if(state.folds.length&&results.length)reason='접힌 선 또는 경계 위의 상이 서로 겹쳐 중복 결과를 하나로 합쳤습니다.';$('#reason').textContent=reason;$('#statusPill').textContent=state.unfoldSteps?`${state.unfoldSteps}/${state.folds.length} 단계 펼침`:`${2**state.folds.length}겹`;$('#stageTitle').textContent=state.mode==='cut'?'종이를 가로지르는 절단선을 그으세요':state.mode==='mission'?'점선 목표 무늬를 만들어 보세요':'접힌 종이 안에서 펀치 위치를 정하세요'}
function reset(keepMode=true){const mode=state.mode;Object.assign(state,{mode:keepMode?mode:'punch',folds:[],poly:square,punch:{x:.72,y:.5,r:Number($('#punchSize').value)/100},cut:null,unfoldSteps:0,selectCut:[],freePoints:[],freeMode:false,mission:keepMode?state.mission:null});render()}
function addFold(){if(state.folds.length>=Number($('#maxFolds').value))return toast('교사가 정한 최대 접기 횟수입니다.');const key=$('#foldLine').value;if(!allowed().includes(key))return toast('현재 허용되지 않은 접기선입니다.');const l=G.presets[key],keep=Number(document.querySelector('[data-keep].chosen')?.dataset.keep||1);try{const poly=G.applyFold(state.poly,l,keep);state.folds.push({line:l,keep});state.poly=poly;state.unfoldSteps=0;const c=G.centroid(poly);state.punch={...c,r:Number($('#punchSize').value)/100};state.cut=null;render()}catch(e){toast(e.message)}}
function position(e){const r=svg.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width*1.2-.1)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height*1.2-.1))}}
svg.addEventListener('pointerdown',e=>{const p=position(e);if(state.freeMode){state.freePoints.push({x:Math.round(p.x*4)/4,y:Math.round(p.y*4)/4});if(state.freePoints.length===2){try{const l=G.lineThrough(...state.freePoints,'자유 접기선');const keep=G.signed(G.centroid(state.poly),l)>=0?1:-1;state.poly=G.applyFold(state.poly,l,keep);state.folds.push({line:l,keep});toast('격자에 맞춘 자유 접기를 추가했습니다.')}catch(err){toast(err.message)}state.freeMode=false;state.freePoints=[]}render();return}if(state.mode==='cut'){state.selectCut.push(p);if(state.selectCut.length===2){const clip=G.clipSegmentPolygon(state.selectCut[0],state.selectCut[1],state.poly);if(!clip){toast('절단선이 접힌 종이와 만나지 않습니다.');state.selectCut=[]}else{state.cut=clip;state.selectCut=[];state.unfoldSteps=0}}render();return}const r=Number($('#punchSize').value)/100;if(!G.circleInsidePolygon(p,r,state.poly))return toast('펀치 전체가 접힌 종이 안에 있어야 합니다.');state.punch={...p,r};state.unfoldSteps=0;render()});
$$('[data-mode]').forEach(b=>b.onclick=()=>{$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));state.mode=b.dataset.mode;$('.action-punch').hidden=state.mode==='cut';$('.action-cut').hidden=state.mode!=='cut';$('.mission-panel').hidden=state.mode!=='mission';reset();if(state.mode==='mission')newMission()});$$('[data-keep]').forEach(b=>b.onclick=()=>{$$('[data-keep]').forEach(x=>x.classList.toggle('chosen',x===b));b.classList.add('chosen')});document.querySelector('[data-keep="1"]').classList.add('chosen');
const actions={manual(){$('#manualDialog').showModal()},closeManual(){$('#manualDialog').close()},fold:addFold,undo(){if(state.folds.pop()){state.poly=square;state.folds.forEach(f=>state.poly=G.applyFold(state.poly,f.line,f.keep));state.unfoldSteps=0;render()}},punch(){toast('펀칭했습니다. 이제 한 단계씩 펼쳐 보세요.');render()},cut(){const c=G.centroid(state.poly),a={x:c.x-.35,y:c.y+.22},b={x:c.x+.35,y:c.y-.22},s=G.clipSegmentPolygon(a,b,state.poly);if(!s)return toast('현재 종이와 만나는 절단선이 없습니다.');state.cut=s;render()},unfold(){if(state.unfoldSteps<state.folds.length){state.unfoldSteps++;render()}else toast('모두 펼쳤습니다.')},all(){state.unfoldSteps=state.folds.length;render()},reset(){reset()},free(){state.freeMode=true;state.freePoints=[];toast('격자 교점 두 곳을 차례로 누르세요.')},save(){const data=collect();localStorage.setItem('ct1-fold-lab',JSON.stringify(data));download(JSON.stringify(data,null,2),'ct1-대칭실험-기록.json','application/json')},print(){print()},fullscreen(){document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()},download:downloadPNG,exportPreset(){const d={version:1,maxFolds:+$('#maxFolds').value,timeLimit:+$('#timeLimit').value,allowedLines:allowed(),hint:$('#teacherHint').value,target:state.mission?.target||null};download(JSON.stringify(d,null,2),'ct1-교사프리셋.json','application/json')},newMission,grade,hint(){if(!state.mission)return;state.hint++;const m=state.hint===1?'완성 무늬의 대칭축을 먼저 찾으세요.':state.hint===2?`첫 접기선은 ${state.mission.hint}입니다.`:'목표 한 점을 접힌 영역으로 반사해 보세요.';$('#missionText').textContent=m}}
$$('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]?.());$('#punchSize').oninput=e=>{$('#sizeOut').textContent=e.target.value;if(state.punch)state.punch.r=e.target.value/100;render()};
function collect(){return{version:1,mode:state.mode,folds:state.folds.map(f=>({id:f.line.id,line:f.line,keep:f.keep})),punch:state.punch,cut:state.cut,prediction:$('#prediction').value,observation:$('#observation').value,explanation:$('#explanation').value}}
function download(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function downloadPNG(){const c=document.createElement('canvas');c.width=c.height=1000;const x=c.getContext('2d');x.fillStyle=state.colors.background;x.fillRect(0,0,1000,1000);x.fillStyle=state.colors.paper;x.fillRect(80,80,840,840);const res=currentResults();x.strokeStyle=state.colors.pattern;x.fillStyle=state.colors.pattern;if(state.mode==='cut'){x.lineWidth=12;res.forEach(s=>{x.beginPath();x.moveTo(80+s.a.x*840,80+s.a.y*840);x.lineTo(80+s.b.x*840,80+s.b.y*840);x.stroke()})}else res.forEach(p=>{x.beginPath();x.arc(80+p.x*840,80+p.y*840,state.punch.r*840,0,Math.PI*2);x.fill()});c.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='ct1-대칭무늬.png';a.click()})}
function newMission(){const d=$('#difficulty').value,defs={easy:{folds:['vertical'],p:{x:.72,y:.5},hint:'세로 중앙선'},normal:{folds:['vertical','horizontal'],p:{x:.72,y:.68},hint:'세로 또는 가로 중앙선'},hard:{folds:['diagDown','vertical'],p:{x:.5,y:.5},hint:'대각선'}};const q=defs[d],folds=q.folds.map(k=>({line:G.presets[k],keep:1}));state.mission={target:G.unfoldPoints([{...q.p}],folds,folds.length),hint:q.hint};state.hint=0;$('#missionText').textContent=`목표: 서로 다른 구멍 ${state.mission.target.length}개 · 최소 접기 ${q.folds.length}회`;render()}
function grade(){if(!state.mission)return;const got=G.unfoldPoints(state.punch?[state.punch]:[],state.folds,state.folds.length),target=state.mission.target;const matched=target.filter(t=>got.some(g=>Math.hypot(g.x-t.x,g.y-t.y)<.035)).length;const precision=got.length?matched/got.length:0,recall=matched/target.length,score=Math.round(100*(precision+recall?2*precision*recall/(precision+recall):0));$('#missionText').textContent=`일치도 ${score}점 · 목표 ${target.length}개 중 ${matched}개 대응 · 사용한 접기 ${state.folds.length}회`;toast(score===100?'정확합니다! 최소 접기도 확인해 보세요.':'대칭축과 펀치 위치를 다시 비교하세요.')}
$('#presetFile').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());$('#maxFolds').value=d.maxFolds??4;$('#timeLimit').value=d.timeLimit??0;$('#allowedLines').value=(d.allowedLines||Object.keys(G.presets)).join(',');$('#teacherHint').value=d.hint||'';if(d.target)state.mission={target:d.target,hint:d.hint||'대칭축'};toast('교사 프리셋을 불러왔습니다.');render()}catch{toast('올바른 JSON 프리셋이 아닙니다.')}};
$$('[data-manual-tab]').forEach(tab=>tab.addEventListener('click',()=>{$$('[data-manual-tab]').forEach(x=>{const on=x===tab;x.classList.toggle('active',on);x.setAttribute('aria-selected',String(on))});$$('[data-manual-page]').forEach(page=>page.hidden=page.dataset.manualPage!==tab.dataset.manualTab)}));
$('#manualDialog').addEventListener('click',e=>{if(e.target===$('#manualDialog'))$('#manualDialog').close()});
render();if(new URLSearchParams(location.search).get('manual')==='1')$('#manualDialog').showModal();
})();
